// https://i.ibb.co/k9MrDDm/VOX.jpg
// https://i.ibb.co/PQv2Lbw/MAESTRO.jpg
// https://i.ibb.co/pQKD5pn/Saturnalia.jpg
// https://i.ibb.co/JnPZbhh/FIDUCIA-AUDITION.jpg

export const events = [
	{
		title: "Verse Wars",
		eventId: "1",
		tagline: "Metres, metaphors, and mesmerising lines",
		category: "LitSoc - Poetry",
		type: "Individual",
		desc: "A poetry slam for you to take your rhyme to the next level. Use your verses, your voice and let the crowd lose themselves to the power of your words.",
		image: "",
		startDate: "",
		endDate: "",
		prize_pool: "8k",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Participants have to submit a video of a performance (not exceeding 3 minutes). The same piece may not be performed at the main event. Limited number of participants will be selected to perform live at Verse Wars.",
					"Same performance rules apply to prelims.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Poems must be original.",
					"Each poem should be a maximum of 3 + 1 minutes. There is no minimum time. Shorter performances will not be penalized.",
					"Poems should not contain offensive remarks to any religion, political party or any section of people. Refrain from triggering controversy via the poems being performed.",
					"Recite poems from memory or read from the page.",
					"A limited number of performers will be allowed on stage.",
					"Team pieces (more than one performer) are fine. The poem being performed must still be an original and the author (one performer) must still be at the centre of the performance.",
					"Poets are encouraged to perform in any language to their suiting. However, a transcript in English has to be provided.",
					"All styles are welcomed and encouraged: a capella hip-hop, theatrical monologues, literary poetry, sound poetry, dub poetry, rants, haikus, power raps, etc.",
					"The delivery of the piece is just as important as the content of the poem. Use your voice and your whole body to perform!",
				],
			},
		],
		contacts: [
			{
				name: "Aditi Singh",
				phone: "+91 80562 91667",
			},
			{
				name: "Haseena Parveen",
				phone: "+91 87905 61966",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "",
		brochure_link: "",
	},
	{
		title: "Flying Solo Vox",
		eventId: "2",
		tagline: "The last one standing",
		category: "Euphony - Music",
		type: "Individual",
		desc: "If your voice is your biggest tool to express yourself through the magic of music, your place is at Flying Solo: Vox, Euphony's music competition for vocalists!",
		image: "https://i.ibb.co/k9MrDDm/VOX.jpg",
		startDate: "",
		endDate: "",
		prize_pool: "5k",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims will be conducted online.",
					"Participants must submit a video of themselves singing a song, not necessarily the song they wish to perform live on the stage of REBECA",
					"Video length should not be more than 5 minutes.",
					"Participants may sing on a pre-decided karaoke track of their own choice/ have one accompaniment (guitarist/pianist). They may also play their own accompanying instrument. However, only the vocals will be considered while scoring.",
					"One submission per participant, and it should be one song only.",
					"Last date of submission 12 April 2023, 11:59 PM. Submission form available on website.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"10 participants will qualify for the final round to perform live.",
					"Only one song is allowed per participant.",
					"Participants may sing on a pre-decided karaoke track of their own choice/ have one accompaniment(guitarist/pianist).",
					"The performance will be judged solely based on Vocals and the accompanying music will not be considered at all either in a negative way or otherwise",
					"The vocalist may play his/her own accompanying instrument, but again only the vocals will be considered while scoring.",
					"Judgment is based on: Accuracy, Dynamics, Proficiency.",
					"Rules stand the same for Online Prelims and for Final Round.",
					"Slot of 7 mins will be allotted including sound check.",
					"Decision of organizers in any stage is final and binding.",
				],
			},
		],
		contacts: [
			{
				name: "Soubhagya Saha",
				phone: "+91 84200 03678",
			},
			{
				name: "Nitu Saha",
				phone: "+91 70447 29906",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "",
		brochure_link: "",
	},
]
