// https://i.ibb.co/k9MrDDm/VOX.jpg
// https://i.ibb.co/PQv2Lbw/MAESTRO.jpg
// https://i.ibb.co/pQKD5pn/Saturnalia.jpg
// https://i.ibb.co/JnPZbhh/FIDUCIA-AUDITION.jpg

export const events = [
	{
		title: "Verse Wars",
		eventId: "1",
		tagline: "Metres, metaphors, and mesmerising lines",
		category: "LitSoc - Poetry",
		type: "Individual",
		desc: "A poetry slam for you to take your rhyme to the next level. Use your verses, your voice and let the crowd lose themselves to the power of your words.",
		image: "",
		startDate: "",
		endDate: "",
		prize_pool: "8k",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Participants have to submit a video of a performance (not exceeding 3 minutes). The same piece may not be performed at the main event. Limited number of participants will be selected to perform live at Verse Wars.",
					"Same performance rules apply to prelims.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Poems must be original.",
					"Each poem should be a maximum of 3 + 1 minutes. There is no minimum time. Shorter performances will not be penalized.",
					"Poems should not contain offensive remarks to any religion, political party or any section of people. Refrain from triggering controversy via the poems being performed.",
					"Recite poems from memory or read from the page.",
					"A limited number of performers will be allowed on stage.",
					"Team pieces (more than one performer) are fine. The poem being performed must still be an original and the author (one performer) must still be at the centre of the performance.",
					"Poets are encouraged to perform in any language to their suiting. However, a transcript in English has to be provided.",
					"All styles are welcomed and encouraged: a capella hip-hop, theatrical monologues, literary poetry, sound poetry, dub poetry, rants, haikus, power raps, etc.",
					"The delivery of the piece is just as important as the content of the poem. Use your voice and your whole body to perform!",
				],
			},
		],
		contacts: [
			{
				name: "Aditi Singh",
				phone: "+91 80562 91667",
			},
			{
				name: "Haseena Parveen",
				phone: "+91 87905 61966",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "",
		brochure_link: "",
	},
	{
		title: "Flying Solo Vox",
		eventId: "2",
		tagline: "The last one standing",
		category: "Euphony - Music",
		type: "Individual",
		desc: "If your voice is your biggest tool to express yourself through the magic of music, your place is at Flying Solo: Vox, Euphony's music competition for vocalists!",
		image: "https://i.ibb.co/k9MrDDm/VOX.jpg",
		startDate: "",
		endDate: "",
		prize_pool: "5k",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims will be conducted online.",
					"Participants must submit a video of themselves singing a song, not necessarily the song they wish to perform live on the stage of REBECA",
					"Video length should not be more than 5 minutes.",
					"Participants may sing on a pre-decided karaoke track of their own choice/ have one accompaniment (guitarist/pianist). They may also play their own accompanying instrument. However, only the vocals will be considered while scoring.",
					"One submission per participant, and it should be one song only.",
					"Last date of submission 12 April 2023, 11:59 PM. Submission form available on website.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"10 participants will qualify for the final round to perform live.",
					"Only one song is allowed per participant.",
					"Participants may sing on a pre-decided karaoke track of their own choice/ have one accompaniment(guitarist/pianist).",
					"The performance will be judged solely based on Vocals and the accompanying music will not be considered at all either in a negative way or otherwise",
					"The vocalist may play his/her own accompanying instrument, but again only the vocals will be considered while scoring.",
					"Judgment is based on: Accuracy, Dynamics, Proficiency.",
					"Rules stand the same for Online Prelims and for Final Round.",
					"Slot of 7 mins will be allotted including sound check.",
					"Decision of organizers in any stage is final and binding.",
				],
			},
		],
		contacts: [
			{
				name: "Soubhagya Saha",
				phone: "+91 84200 03678",
			},
			{
				name: "Nitu Saha",
				phone: "+91 70447 29906",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "",
		brochure_link: "",
	},
	{
		title: "Voice of REBECA",
		eventId: "3",
		tagline: "Kickstart your unplugged heart",
		category: "Euphony - Music",
		type: "Team",
		desc: "Sway the crowd to the rhythms of your guitar, let the audience lose themselves to your mystic voice, Euphony presents the acoustic music competition, Voice of REBECA!",
		image: "",
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims will be conducted online.",
					"Participants must submit a video of a song being performed by their band, it can be a cover song or can be an original song.",
					"Video length should not be more than 6 minutes.",
					"All kinds of acoustic instruments are allowed, including drums. Electric bass can be allowed if necessary. Synthesizer can be used, but only piano and strings patches are allowed. Electric guitars and any other instruments which has a processed sound are not allowed except above-mentioned cases.",
					"Maximum band members in a band can be 7, minimum is 2.",
					"One submission per band, and it should be one song only.",
					"You don't necessarily need to perform the same song in live stage of REBECA.",
					"Last date of submission 12 April 2023, 11:59 PM. Submission form available on website.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"10 teams will qualify for the final round to perform live on stage of REBECA. (Not necessarily the same song has to be performed).",
					"Each band can perform only one song. Choice of Song: Can be a cover or original song.",
					"Any electric guitars or any other instruments which have a processed sound are not allowed. Electric bass is allowed, but without a processor.",
					"All kinds of acoustic instruments are allowed including drums and Acoustic Bass.",
					"Synthesizer could be used but only piano and strings patches are allowed.",
					"Any kind of backing track is not allowed.",
					"Maximum number of members allowed per band 7, minimum 2.",
					"Only a standard 6-piece drum set will be provided. Participants need to bring their own instruments. Final technical supplies will be informed later.",
					"Slot of 10 mins will be allocated to each band including sound check",
					"Judging Criteria: Accuracy, Dynamics, Stage Presence, Proficiency, Arrangement",
					"Decision of organizers in any stage is final and binding.",
				],
			},
		],
		contacts: [
			{
				name: "Priyangshu Pramanick",
				phone: "+91 79085 92431",
			},
			{
				name: "Rishav Verma",
				phone: "+91 96744 31870",
			},
		],
		registration_amount: "Rs. 500",
		registration_amount_iiest: "Rs. 500",
		payment_link_iiest: "",
		payment_link: "",
		brochure_link: "",
	},
	{
		title: "RockBuzz",
		eventId: "4",
		tagline: "War cries in harmony",
		category: "Euphony - Music",
		type: "Team",
		desc: "Euphony brings together the most powerful college bands all over the nation in this fierce battle. Let great music reign over the war of bands!",
		image: "",
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims will be conducted online.",
					"Participants must submit a video of a song being performed by their band, it can be a cover song or can be an original song.",
					"Video length should not be more than 7 minutes.",
					"Maximum number of members in a band can be 8, minimum is.",
					"One submission per band, and it should be one song only.",
					"Using plugins is allowed, but any kind of backing track is not allowed.",
					"You don't necessarily need to perform the same song in live stage of REBECA.",
					"Last date of submission 16 April 2023, 11:59 PM. Submission form available on website.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"10 teams will qualify for the final round to perform live on stage of REBECA. (Not necessarily the same song has to be performed).",
					"Choice of Song: Can be a cover or original song.",
					"Using plugins is allowed.",
					"Any kind of backing track is not allowed.",
					"Only one song per band.",
					"Maximum number of members allowed per band 8, minimum 3",
					"Only a standard 6-piece drum set will be provided. Participants need to bring their own instruments.",
					"Slot of 15 mins will be allocated to each band including sound check",
					"Judging Criteria: Accuracy, Dynamics, Stage Presence, Proficiency, Arrangement",
					"Decision of organizers in any stage is final and binding",
					"Final technical supplies will be informed later.",
				],
			},
		],
		contacts: [
			{
				name: "Rahi Abrar",
				phone: "+91 93303 06957",
			},
			{
				name: "Rishav Verma",
				phone: "+91 96744 31870",
			},
		],
		registration_amount: "Rs. 500",
		registration_amount_iiest: "Rs. 500",
		payment_link_iiest: "",
		payment_link: "",
		brochure_link: "",
	},
]
