import verse from "../assets/events/Verse Wars.png"
import vox from "../assets/events/Flying Solo Vox.jpg"
import voice from "../assets/events/VOICE OF REBECA.jpg"
import rockbuzz from "../assets/events/Rockbuzz.png"
import maestro from "../assets/events/MAESTRO.jpg"
import rap from "../assets/events/RAPSODIES.jpg"
import nukkad from "../assets/events/Nukkad.png"
import silence from "../assets/events/Expressive Silence.png"
import mudra from "../assets/events/Mudra.png"
import nartana from "../assets/events/nartana.png"
import groove from "../assets/events/GROOVE.jpg"
import scape from "../assets/events/RHYTHMSCAPE.jpg"
import loose from "../assets/events/FOOTLOOSE.jpg"
import kala from "../assets/events/Kalakriti.png"
import shastra from "../assets/events/Shastrath.png"
import barter from "../assets/events/barter to survive.png"
import buffer from "../assets/events/Buffer.png"
import rebecsal from "../assets/events/Rebecsal.png"
import rebequiz from "../assets/events/Rebequiz.png"

import artival from "../assets/events/Artival.png"
import cinessence from "../assets/events/Cinessence.png"
import fiducia from "../assets/events/fiducia main.jpg"
import filmica from "../assets/events/Filmica.png"
import rangmanch from "../assets/events/RANGAMANCH COMBO.jpg"
import saturnalia from "../assets/events/saturnalia.jpg"
import typist from "../assets/events/Typist_s Tourney.png"

export const events = [
	{
		title: "Verse Wars",
		eventId: "1",
		tagline: "Metres, metaphors, and mesmerising lines",
		category: "LitSoc - Poetry",
		type: "Individual",
		desc: "A poetry slam for you to take your rhyme to the next level. Use your verses, your voice and let the crowd lose themselves to the power of your words.",
		image: verse,
		startDate: "",
		endDate: "",
		prize_pool: "8k",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Participants have to submit a video of a performance (not exceeding 3 minutes). The same piece may not be performed at the main event. Limited number of participants will be selected to perform live at Verse Wars.",
					"Same performance rules apply to prelims.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Poems must be original.",
					"Each poem should be a maximum of 3 + 1 minutes. There is no minimum time. Shorter performances will not be penalized.",
					"Poems should not contain offensive remarks to any religion, political party or any section of people. Refrain from triggering controversy via the poems being performed.",
					"Recite poems from memory or read from the page.",
					"A limited number of performers will be allowed on stage.",
					"Team pieces (more than one performer) are fine. The poem being performed must still be an original and the author (one performer) must still be at the centre of the performance.",
					"Poets are encouraged to perform in any language to their suiting. However, a transcript in English has to be provided.",
					"All styles are welcomed and encouraged: a capella hip-hop, theatrical monologues, literary poetry, sound poetry, dub poetry, rants, haikus, power raps, etc.",
					"The delivery of the piece is just as important as the content of the poem. Use your voice and your whole body to perform!",
				],
			},
		],
		contacts: [
			{
				name: "Aditi Singh",
				phone: "+91 80562 91667",
			},
			{
				name: "Haseena Parveen",
				phone: "+91 87905 61966",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/WU46VYzgme3aoS6c6",
		brochure_link: "",
	},
	{
		title: "Flying Solo Vox",
		eventId: "2",
		tagline: "The last one standing",
		category: "Euphony - Music",
		type: "Individual",
		desc: "If your voice is your biggest tool to express yourself through the magic of music, your place is at Flying Solo: Vox, Euphony's music competition for vocalists!",
		image: vox,
		startDate: "",
		endDate: "",
		prize_pool: "5k",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims will be conducted online.",
					"Participants must submit a video of themselves singing a song, not necessarily the song they wish to perform live on the stage of REBECA",
					"Video length should not be more than 5 minutes.",
					"Participants may sing on a pre-decided karaoke track of their own choice/ have one accompaniment (guitarist/pianist). They may also play their own accompanying instrument. However, only the vocals will be considered while scoring.",
					"One submission per participant, and it should be one song only.",
					"Last date of submission 12 April 2023, 11:59 PM. Submission form available on website.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"10 participants will qualify for the final round to perform live.",
					"Only one song is allowed per participant.",
					"Participants may sing on a pre-decided karaoke track of their own choice/ have one accompaniment(guitarist/pianist).",
					"The performance will be judged solely based on Vocals and the accompanying music will not be considered at all either in a negative way or otherwise",
					"The vocalist may play his/her own accompanying instrument, but again only the vocals will be considered while scoring.",
					"Judgment is based on: Accuracy, Dynamics, Proficiency.",
					"Rules stand the same for Online Prelims and for Final Round.",
					"Slot of 7 mins will be allotted including sound check.",
					"Decision of organizers in any stage is final and binding.",
				],
			},
		],
		contacts: [
			{
				name: "Soubhagya Saha",
				phone: "+91 84200 03678",
			},
			{
				name: "Nitu Saha",
				phone: "+91 70447 29906",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/QHG4LfQQYZvbaKaT7",
		brochure_link: "",
	},
	{
		title: "Voice of REBECA",
		eventId: "3",
		tagline: "Kickstart your unplugged heart",
		category: "Euphony - Music",
		type: "Team",
		desc: "Sway the crowd to the rhythms of your guitar, let the audience lose themselves to your mystic voice, Euphony presents the acoustic music competition, Voice of REBECA!",
		image: voice,
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims will be conducted online.",
					"Participants must submit a video of a song being performed by their band, it can be a cover song or can be an original song.",
					"Video length should not be more than 6 minutes.",
					"All kinds of acoustic instruments are allowed, including drums. Electric bass can be allowed if necessary. Synthesizer can be used, but only piano and strings patches are allowed. Electric guitars and any other instruments which has a processed sound are not allowed except above-mentioned cases.",
					"Maximum band members in a band can be 7, minimum is 2.",
					"One submission per band, and it should be one song only.",
					"You don't necessarily need to perform the same song in live stage of REBECA.",
					"Last date of submission 12 April 2023, 11:59 PM. Submission form available on website.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"10 teams will qualify for the final round to perform live on stage of REBECA. (Not necessarily the same song has to be performed).",
					"Each band can perform only one song. Choice of Song: Can be a cover or original song.",
					"Any electric guitars or any other instruments which have a processed sound are not allowed. Electric bass is allowed, but without a processor.",
					"All kinds of acoustic instruments are allowed including drums and Acoustic Bass.",
					"Synthesizer could be used but only piano and strings patches are allowed.",
					"Any kind of backing track is not allowed.",
					"Maximum number of members allowed per band 7, minimum 2.",
					"Only a standard 6-piece drum set will be provided. Participants need to bring their own instruments. Final technical supplies will be informed later.",
					"Slot of 10 mins will be allocated to each band including sound check",
					"Judging Criteria: Accuracy, Dynamics, Stage Presence, Proficiency, Arrangement",
					"Decision of organizers in any stage is final and binding.",
				],
			},
		],
		contacts: [
			{
				name: "Priyangshu Pramanick",
				phone: "+91 79085 92431",
			},
			{
				name: "Rishav Verma",
				phone: "+91 96744 31870",
			},
		],
		registration_amount: "Rs. 500",
		registration_amount_iiest: "Rs. 500",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/yD9m9QXZaf4s7Lzo9",
		brochure_link: "",
	},
	{
		title: "RockBuzz",
		eventId: "4",
		tagline: "War cries in harmony",
		category: "Euphony - Music",
		type: "Team",
		desc: "Euphony brings together the most powerful college bands all over the nation in this fierce battle. Let great music reign over the war of bands!",
		image: rockbuzz,
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims will be conducted online.",
					"Participants must submit a video of a song being performed by their band, it can be a cover song or can be an original song.",
					"Video length should not be more than 7 minutes.",
					"Maximum number of members in a band can be 8, minimum is.",
					"One submission per band, and it should be one song only.",
					"Using plugins is allowed, but any kind of backing track is not allowed.",
					"You don't necessarily need to perform the same song in live stage of REBECA.",
					"Last date of submission 16 April 2023, 11:59 PM. Submission form available on website.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"10 teams will qualify for the final round to perform live on stage of REBECA. (Not necessarily the same song has to be performed).",
					"Choice of Song: Can be a cover or original song.",
					"Using plugins is allowed.",
					"Any kind of backing track is not allowed.",
					"Only one song per band.",
					"Maximum number of members allowed per band 8, minimum 3",
					"Only a standard 6-piece drum set will be provided. Participants need to bring their own instruments.",
					"Slot of 15 mins will be allocated to each band including sound check",
					"Judging Criteria: Accuracy, Dynamics, Stage Presence, Proficiency, Arrangement",
					"Decision of organizers in any stage is final and binding",
					"Final technical supplies will be informed later.",
				],
			},
		],
		contacts: [
			{
				name: "Rahi Abrar",
				phone: "+91 93303 06957",
			},
			{
				name: "Rishav Verma",
				phone: "+91 96744 31870",
			},
		],
		registration_amount: "Rs. 500",
		registration_amount_iiest: "Rs. 500",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/dCqYU8wDcrC3Az136",
		brochure_link: "",
	},
	{
		title: "Flying Solo Maestro",
		eventId: "5",
		tagline: "The last one standing",
		category: "Euphony - Music",
		type: "Individual",
		desc: "Does the wizard inside you take over whenever you put your hands on your musical instrument? Euphony's Flying Solo: Maestro is the stage for you, let the melody and rhythm flow through the crowd!",
		image: maestro,
		startDate: "",
		endDate: "",
		prize_pool: "5K",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims will be conducted online.",
					"Participants must submit a video of themselves performing an instrumental cover of a song.",
					"Video length should not be more than 5 minutes.",
					"Plugins are allowed",
					"One submission per participant, and it should be one song only.",
					"Last date of submission 16 April 2023, 11:59 PM. Submission form available on website",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims would include an instrumental cover of any song.",
					"10 participants will qualify for the final round to perform live.",
					"Participants need to improvise on a backing track provided by us.",
					"Plugins are allowed",
					"A choice of tracks will be given prior to the final round amongst which participants can choose, on which they would have to improvise. They can’t vary the scale or tempo of the chosen backing track.",
					"Judgment is based on: Accuracy, Dynamics, Proficiency.",
					"Slot of 10 mins will be allotted including sound check.",
					"Decision of organizers in any stage is final and binding",
				],
			},
		],
		contacts: [
			{
				name: "Rahi Abrar",
				phone: "+91 93303 06957",
			},
			{
				name: "Rishav Verma",
				phone: "+91 96744 31870",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/G9owTYYQHBQ6whTU8",
		brochure_link: "",
	},
	{
		title: "Rapsodies",
		eventId: "6",
		tagline: "All Eyez on You",
		category: "Euphony - Music",
		type: "Individual",
		desc: "Are you a poet of the new generation, and all you need is a beat to drop some bars to elevate the crowd? We'll save you a slot at Euphony's rap competition!",
		image: rap,
		startDate: "",
		endDate: "",
		prize_pool: "7K",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Prelims will be conducted online.",
					"Participants must choose any topic they want, write and perform a rap on that.",
					"Participants must make a video of them rapping, video length must not be more than 3 minutes",
					"Backing tracks are allowed",
					"Any sort of racist, sexist or directly offensive slurs will lead to immediate disqualification.",
					"Only one entry is permitted per participant",
					"Language of rap must be Hindi, English or Bengali.",
					"Recording of the video must be done without any pauses, whole video should be recorded together and not by parts.",
					"Note that, the audio and video must not be processed or altered in any way. Using any kinds of special effects is STRICTLY prohibited and will lead to disqualification.",
					"Last date of submission 16 April 2023, 11:59 PM. Submission form available on website.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Participants need to freestyle rap on a track that will be provided to them just prior to the final round.",
					"A choice of themes would be given on which the participant needs to freestyle.",
					"No vulgar language and no use of Alcohol, cigarettes or any illegal substance.",
					"Participants are allowed to use puns, double-entendres and quips but any kind of direct implication, sexist or racist slurs will lead to disqualification.",
					"The language of rap will be Bengali, Hindi or English.",
					"Groups are also allowed. Maximum 3 members allowed",
					"The points will be given based on Originality, Technicality and Stage Presence.",
					"Decisions of organizers will be the final and binding in any case",
				],
			},
		],
		contacts: [
			{
				name: "Rishav Verma",
				phone: "+91 96744 31870",
			},
			{
				name: "Priyangshu Pramanick",
				phone: "+91 79085 9243",
			},
		],
		registration_amount: "Rs. 150",
		registration_amount_iiest: "Rs. 150",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/CWmJpDtnqhXTFLQY7",
		brochure_link: "",
	},
	{
		title: "Nukkad",
		eventId: "7",
		tagline: "Bringing the stage to the street",
		category: "Les Thespians - Dramatics",
		type: "Team",
		desc: "Nukkad, our street play competition. Get ready to portray your feelings on serious social issues through Nukkad.",
		image: nukkad,
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Team Size: 10-30 (including CAs & music accompanists)",
					"Teams have to mail the following things at (Rebeca Event team email id): Synopsis of the play (not more than 100 words) and Prod List (List of production material and music instruments brought by the teams). The subject of the email should be “NUKKADCollege_name-Play_name” before the mentioned deadline.",
					"Time Limit: 15-30minutes. Points will be deducted on exceeding the time limit.",
					"Judging Criteria: Acting, Voice (Sync, modulation and diction) Screenplay, Script, Audience Interaction & overall impact",
					"The team size represents the number of people registered as a team. Only these shall be allowed to perform the Street play.",
					"Music accompanists are included in the team number stated above. Maximum of 4 can be included in the team.",
					"Teams are expected to perform at an open-air venue with the audience all around.",
					"No electrical appliances shall be allowed during the performance whether inside or outside the circle of performance.",
					"Only live music is allowed. Teams will have to bring the instruments. No instruments will be provided.",
					"The language of the performance should be Hindi/English/Bengali. However, short sub passages in other languages are allowed.",
					"Any fluid, live animals, flames, heavy objects or any material which has a possibility of damaging the stage is not allowed.",
					"Dry colours may be used during the play, but the teams have to clean the stage after their performance & the cleaning time will be included in the performance time.",
					"Any plagiarism & profanity will lead to immediate disqualification.",
					"The decision of the judges and organizers will be final & abiding.",
				],
			},
		],
		contacts: [
			{
				name: "Ankush Sahu",
				phone: "+91 9616934988",
			},
			{
				name: "Prerona Saha",
				phone: "+91 9062038149",
			},
		],
		registration_amount: "Rs. 500",
		registration_amount_iiest: "Rs. 500",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/pe8tQjJBGjcafKMd8",
		brochure_link: "",
	},
	{
		title: "Expressive Silence",
		eventId: "8",
		tagline: "Silence speaks volumes: let your expressions do the talking!",
		category: "Les Thespians - Dramatics",
		type: "Team",
		desc: "An event where performers showcase their skills in the art of mime, using only body language and gestures to convey a story or message. Mime is a universal art form that transcends language and cultural barriers, allowing performers to communicate with audiences around the world.",
		image: silence,
		startDate: "",
		endDate: "",
		prize_pool: "5K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Team Limit: 8+2persons (max)",
					"Time Limit: 10minutes",
					"Unnecessary use of props is discouraged.",
					"Face painting and costumes would not be considered as a prop.",
					"The act should not contain any dialogues, lip syncs.",
					"Background music is allowed. However, it must not contain any words (sound representing any living form is not allowed).",
					"The decision of judges will be final and binding.",
					"Any fluid/flame is not allowed.",
					"No act shall contain any obscene, disrespectful actions or gestures. The act will immediately be stopped, and entry will be disqualified if these instructions are not followed.",
					"Judging criteria: Acting, expression & overall impact.",
				],
			},
		],
		contacts: [
			{
				name: "Ashutosh Kumar Manjhi",
				phone: "+91 6488649291",
			},
			{
				name: "Subhomoy Gupta",
				phone: "+91 7431955333",
			},
		],
		registration_amount: "Rs. 400",
		registration_amount_iiest: "Rs. 400",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/tRuMRjNgAjHqW26SA",
		brochure_link: "",
	},
	{
		title: "Mudra",
		eventId: "9",
		tagline: "Catch the Classical Pace",
		category: "Reflexobeta - Dance",
		type: "Individual",
		desc: "Yatho Hasta thatho Drishti, Yatho Drishti thatho Manah, Yatho Manah thatho Bhaava, Yatho Bhaava thatho Rasa. Where the hands are, the eyes follow. Where the eyes are, the mind follows, which auspicate flow of expressions and where there is expression, Navarasa is evoked. So get ready to give an explosion of grace, strength and artistry on stage as we unveil “Mudra”, The Classical Solo Dance Competition",
		image: mudra,
		startDate: "",
		endDate: "",
		prize_pool: "6K",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Submit your dance video (single take, stationary camera, no editing) of max 2 minutes duration at the time of registration.",
					"Upload your video in google drive with general access, and upload the drive link in the registration form.",
					"The video should be in landscape mode and audible with good sound quality.",
					"The video should be visually clear, well-lit, not pixelated or distorted, and have an uncluttered background",
					"The top 15 entries will qualify for the next round",
					"Last date of entry: 12 April 2023, 11:59 pm",
					"Props are allowed but will not fetch extra points.",
					"Video submission form will be available on website.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Finals will be conducted offline during Rebeca at IIEST, Shibpur",
					"Props are allowed and will carry extra points",
					"Participants will be marked on their Expressions, Costumes, Stage utilization, Energy, Authenticity, and Perfection.",
					"Maximum time limit: 6 minutes",
					"Judge's decision will be final and binding",
				],
			},
		],
		contacts: [
			{
				name: "Navya Jain",
				phone: "+91 9414241104",
			},
			{
				name: "Sri Anjani Samala",
				phone: "+91  9391763989",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/vWDHu2HfkW3AsNKs9",
		brochure_link: "",
	},
	{
		title: "Nartana",
		eventId: "10",
		tagline: "Dancing in Circles and Cultures",
		category: "Reflexobeta - Dance",
		type: "Team",
		desc: "Our ancestors have gifted us with scriptures and dances which best portray our history and culture. We invite you all to bring along the heritage, thrill and beauty of classical and folk dances upon the stage for “Nartana”, the Classical/Folk Group Dance Competition and mesmerise the audience.",
		image: nartana,
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"This competition has only one round.",
					"It will be conducted offline during Rebeca at IIEST, Shibpur.",
					"Team can consist of 5 - 20 members",
					"More than 1 team is allowed from the same college",
					"Cross college teams are allowed.",
					"One student cannot be part of multiple groups for the same competition.",
					"Participants must carry their School/College ID cards.",
					"Props are allowed and will carry extra points",
					"All classical and folk-dance forms are allowed",
					"Marks will be based on: Synchronization and rhythm, Coordination among participants, Extent of perfection in mudras &, Postures, Dance formations, Expression.",
					"Maximum time limit: 10 minutes (including stage setup)",
					"At any given time, minimum 3 members should be present on stage.",
					"Judge's decision will be final and binding.",
				],
			},
		],
		contacts: [
			{
				name: "Gorle Sirisha",
				phone: "+91 9515066025",
			},
			{
				name: "Debarya Saha",
				phone: "+91  9123652261",
			},
		],
		registration_amount: "Rs. 400",
		registration_amount_iiest: "Rs. 400",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/5iuM3iZEQc46Tb2R6",
		brochure_link: "",
	},
	{
		title: "Groove",
		eventId: "11",
		tagline: "Create and Prance ",
		category: "Reflexobeta - Dance",
		type: "Individual",
		desc: "You rise, you fall, you spin and you crawl, Life is like dance, and worth enjoying it all. So, lace up your dancing shoes, pick up those classy beats and get ready to show off your moves in “Groove”, the Western Solo Dance Competition. Let’s see who transcends through all boundaries with the language of dance.",
		image: groove,
		startDate: "",
		endDate: "",
		prize_pool: "6K",
		rounds: [
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Submit your dance video (single take, stationary camera, no editing)) of max 2 minutes duration at the time of registration.",
					"Upload your video in google drive with general access, and upload the drive link in the registration form. ",
					"The video should be in landscape mode and audible with good sound quality.",
					"The video should be visually clear, well-lit, not pixelated or distorted, and have an uncluttered background",
					"The top 15 entries will qualify for the next round",
					"Last date of entry: 12 April 2023, 11:59 pm",
					"Props are allowed but will not fetch extra points.",
					"Video submission form will be available on website",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Finals will be conducted offline during Rebeca at IIEST, Shibpur",
					"Participants must carry their School/College ID cards",
					"Props are allowed and will carry extra points",
					"Participants will be marked on their Expressions, Costumes, Stage utilization, Energy, Authenticity, and Perfection.",
					"Maximum time limit: 6 minutes",
					"Judge’s decision will be final and binding",
				],
			},
		],
		contacts: [
			{
				name: "Tanisha Ghosh",
				phone: "+91 82580 04761",
			},
			{
				name: "Athena A Shaji",
				phone: "+91 82815 88297",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/ShT3JrhsJMiiE2Bj6",
		brochure_link: "",
	},
	{
		title: "Rhythmscape",
		eventId: "12",
		tagline: "Music, Meanders and Magic on Stage",
		category: "Reflexobeta - Dance",
		type: "Team",
		desc: "Dance is a form of expression, a light hearted celebration which gets better when you have a group to sync your steps with. Fascinate the crowd with your style and energy and get them grooving with your troop in the Western Group Dance Competition, “Rhythmscape”. Get them all swaying.",
		image: scape,
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"This competition has only one round",
					"It will be conducted offline during Rebeca at IIEST, Shibpur. ",
					"Team can consist of 5 - 20 members",
					"More than 1 team is allowed from the same college.",
					"Cross college teams are allowed.",
					"One student cannot be part of multiple groups for the same competition",
					"Participants must carry their School/College ID cards",
					"Props are allowed and will carry extra points.",
					"All classical and folk-dance forms are allowed",
					"Marks will be based on: Synchronization and rhythm,  Coordination among participants, Extent of perfection and energy, Dance formations, Expression.",
					"Maximum time limit: 10 minutes (including stage setup)",
					"At any given time, minimum 3 members should be present on stage.",
					"Judge's decision will be final and binding.",
				],
			},
		],
		contacts: [
			{
				name: "Poorva Mondal",
				phone: "+91 8436376729",
			},
			{
				name: "Tannishtha Bag",
				phone: "+91 8587825869",
			},
		],
		registration_amount: "Rs. 400",
		registration_amount_iiest: "Rs. 400",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/PGjGDpH3NnqnKyEK7",
		brochure_link: "",
	},
	{
		title: "Footloose",
		eventId: "13",
		tagline: "Clash of Dancing Mobs",
		category: "REFLEXOBETA - Dance",
		type: "Team",
		desc: "A street dance competition is a thrilling and dynamic event that showcases the raw talent, creativity, and passion of dancers from all over. Footloose brings the best dancers from across the country to come together and celebrate the  diverse and vibrant world of urban dance through competitive dance face offs. If you think you have the perfect skills to set the streets on fire, then grab this chance fast, the winner’s position is at stake! Let’s see who will be crowned the champion.",
		image: loose,
		startDate: "",
		endDate: "",
		prize_pool: "6K",
		rounds: [
			{
				title: "General rule",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Minimum 4 and maximum 8 dancers per team.",
					"The faceoff can have a solo dancer, a duo, or the entire team.",
					"There will be only knock-out rounds. The last two best teams remaining will faceoff for the winning position.",
					"The dance floor area must be in the same condition after the performances as before.",
					"No props will be provided",
					"Individuality and originality of the dance are encouraged as well as interaction and contact with the spectators and the other dancers.",
					"Dancers are not restricted from performing any move, but they must be aware that it is their responsibility to ensure that they do not perform critical steps that could injure themselves or others. Coordinators have the right to bring in safety restrictions.",
					"The use of harmless props is allowed.",
					"Eligible participants: College students only. Teams having students from different colleges are allowed",
				],
			},
			{
				title: "Prelims",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"It is a knock-out based event. The team that wins a round goes to the next level.",
					"Teams alternatively take turns to showcase their skills, either through individual or group performance.",
					"All the participating teams should send a playlist containing four songs on which they would like to perform in the street dance faceoff.",
					"The songs submitted will be shuffled and played during the faceoff.",
					"Each turn lasts for a minute, and each team gets two such turns.",
				],
			},
			{
				title: "Finals",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"A coin toss decides which team goes first.",
					"The Music for the performances will be provided on spot.",
					"The teams will be given 4 turns alternative, each of 1 minute in the semi-final and the final round.",
				],
			},
		],
		contacts: [
			{
				name: ": Chandra Bhushan",
				phone: "+91 9334898243",
			},
			{
				name: "Palla Pavan",
				phone: "+91 9963489861",
			},
		],
		registration_amount: "Rs. 250",
		registration_amount_iiest: "Rs. 250",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/Ux1pGwF8MaxUKEcr9",
		brochure_link: "",
	},
	{
		title: "Kalakriti",
		eventId: "14",
		tagline: "A time travel to the Golden period of Art, Renaissance",
		category: "SCAGE - Art",
		type: "Individual",
		desc: "If time travel were possible, one period we should really explore would be the Renaissance, the age of artists and creative minds. Open to artists from our college and beyond, there is no better opportunity to venture into your creative side than through an Renaissance themed art competition, which includes realism, perspective, and the use of light and shadow. The entries will be judged based on creativity, originality, technical skill, and their ability to capture the essence of Renaissance. You might never know if you can create the next 'Mona Lisa'!",
		image: kala,
		startDate: "",
		endDate: "",
		prize_pool: "8K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"This will be an offline competition.",
					"Participants must bring all the stationery they wish to use.",
					"Drawing sheets will be provided",
					"Judging Criteria: Creativity, relevance to theme, authenticity, uniqueness.",
					"Artwork must be based on any traditional/folk/tribal art form of India.",
					"Participants will be given 3 hours to complete their artwork.",
					"Taking reference from external sources during the competition is not allowed.",
					"Decision of judges will be final and binding.",
				],
			},
		],
		contacts: [
			{
				name: "Devanshu Chatterjee",
				phone: "+91 73551 64558",
			},
			{
				name: "Nikhil Singh",
				phone: "+91 74898 38247",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/oSu2aettzVB9s8Vu6",
		brochure_link: "",
	},
	{
		title: "REBEQuiz",
		eventId: "15",
		tagline: "Test Your Knowledge with REBEQUIZ",
		category: "QUIZMANIAC BEINGS - Quiz",
		type: "Team",
		desc: "Get ready to lock your horns and test your wits to witness the rebirth of the Ultimate Quiz in Rebeca. Presenting to you REBEQUIZ! We welcome all quizzing enthusiasts to showcase their knowledge and skills. Test your knowledge and quick-thinking skills in this exciting trivia event, and face your rivals in this race to come out on top.",
		image: rebequiz,
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Maximum age-limit for participants is 25 years.",
					"Cross-college teams are allowed.",
					"Teams of up to 3 members are allowed.",
					"Participation certificates for all.",
					"Theme - Media, Entertainment, Literature, Arts and Sports (MELA)",
					"Prelims will be conducted before the main quiz.",
				],
			},
		],
		contacts: [
			{
				name: "Saptarsi Chakrabarty",
				phone: "+91 90516 86453",
			},
			{
				name: "Souvik Sengupta",
				phone: "+91 82505 64473",
			},
		],
		registration_amount: "Rs. 150",
		registration_amount_iiest: "Rs. 150",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/9RqUjgQ7saBm3Byp7",
		brochure_link: "",
	},
	{
		title: "Shastrartha",
		eventId: "16",
		tagline: "Race to refute",
		category: "DEBSOC - Debate",
		type: "Team",
		desc: "Join us in this pursuit of Dispute to witness the rediscovery and rebirth of debate in REBECA, Presenting to you, Rebuttal Rebels, a 3v3 Asian Parliamentary Debate with exciting cash prizes and some fierce debating! Listen. Think. Speak and dissent to become Arguably the Best of them all with exciting cash prizes and eminent debaters as judges.",
		image: shastra,
		startDate: "",
		endDate: "",
		prize_pool: "8K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Each team shall consist of 3 members. Each debating match will consist of two teams; one to propose the motion and one to oppose it. The team proposing may be known as ‘The Proposition’, ‘The Affirmative’ or ‘The Government’. The team opposing may be known as ‘The Opposition’ or ‘The Negative’. Teams will be designated as the Proposition or the Opposition for each round of the competition.",
					"The time allotted to each speaker is 3 minutes (for the speakers) and 1 minute for the reply speech.",
					"The verdict of the chair shall remain final.",
					"Each debate shall be timed by a timekeeper. In the absence of a timekeeper a member of the panel shall time debate.",
				],
			},
		],
		contacts: [
			{
				name: "Darshin Patel",
				phone: "+91 9415862800",
			},
			{
				name: "Sayantan Paul",
				phone: "+91 98306 64404",
			},
		],
		registration_amount: "Rs. 150",
		registration_amount_iiest: "Rs. 150",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/Tot1Bcb94DiDn4E7A",
		brochure_link: "",
	},
	{
		title: "Barter to Survive",
		eventId: "17",
		tagline: "Where acumen meets industry",
		category: "EDC - Business",
		type: "Team",
		desc: "Buckle up and get ready in order to survive and make a way to succeed here. One team draws a set of creativity moves while the others follow the suits to survive. Without preparing in advance, players present convincing moves showing their creativity, negotiation, survival and communication skills",
		image: barter,
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"Player one from a team chooses a player and suggests a trade. For example, player one may offer player two a horse for transportation in exchange for seeds to grow crops.",
					"If the player who was offered the trade does not have the requested item in his hand of any of team members, player one’s turn ends and the game continues with the next team.",
					"If the player who was offered the trade has the requested item in his hand, he may accept the trade or offer a counter trade. For example, he may request that player one give him a horse and water in exchange for the seeds.",
					"Player one can accept the counter trade or present another counter trade. For example, player one may say “I don’t have any water, but I will give you a horse and clothing in exchange for water.",
					"The player who was offered the trade can accept the counter trade or stick to his original offer. If he sticks to his original offer, player one can accept that offer or deny it, and allow play to move on to the next player.",
					"The next team player chooses a player and suggests a trade.",
					"Bartering/trading continues in the same way until one player has all 10 basic needs in his hand.",
				],
			},
		],
		contacts: [
			{
				name: "Disha Trivedi",
				phone: "+91 6290625109",
			},
			{
				name: "Arnav Anand",
				phone: "+91 7061991256",
			},
		],
		registration_amount: "Rs. 50",
		registration_amount_iiest: "Rs. 50",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/VfetUmTDNmFaAcZf9",
		brochure_link: "",
	},
	{
		title: "Buffer",
		eventId: "18",
		tagline: "Unleashing Cinematic Creativity",
		category: "CAMERABUFF - Film Making",
		type: "Team",
		desc: "Everyone is a filmmaker at least once in a lifetime. Camerabuff presents a short filmmaking competition to give one the opportunity to showcase their filmmaking skills.",
		image: buffer,
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"This is an offline event. The theme will be announced at the start of the event on 20/04/23, 8:00 PM IST and teams will be given 50 hours of time period.",
					"Length of the short film must not exceed 15 minutes, including credits.",
					"Subtitles are mandatory; if the language of the short film is not in Hindi/English.",
					"Vulgarity of any kind shall result in direct disqualification.",
					"Music and SFX are allowed, but with due credits to its original creators.",
					"Stock footage and prior shot clips are not allowed to be used. If some discrepancies are found then raw footages of the clip could be asked for proper checking",
					"The deadline for submitting your short film is 22/04/23, 10:00 PM IST.",
					"The decisions of the judges shall be final and binding.",
					"Camerabuff, IIESTS reserves the right to publish any of the entries on its page as well as allied handles",
				],
			},
		],
		contacts: [
			{
				name: "Disha Trivedi",
				phone: "+91 6290625109",
			},
			{
				name: "Arnav Anand",
				phone: "+91 7061991256",
			},
		],
		registration_amount: "Rs. 250",
		registration_amount_iiest: "Rs. 250",
		payment_link_iiest: "",
		payment_link: "https://forms.gle/1QD22akRUUKLgjEs5",
		brochure_link: "",
	},
	{
		title: "Rebecsal",
		eventId: "19",
		tagline: "Put your best foot forward",
		category: "SPORTS",
		type: "Team",
		desc: "Gather your mates and showcase your skill, stamina, partnerships and sportsmanship in this grand game of futsal!.",
		image: rebecsal,
		startDate: "",
		endDate: "",
		prize_pool: "10K",
		rounds: [
			{
				title: "Single round",
				desc: "",
				date: "",
				time: "",
				duration: "",
				venue: "",
				locUrl: "",
				rules: [
					"The Tournament is of Knockout format and the fixture will be decided totally on lottery basis.",
					"Each player must have a pair of joggers or football studs. Running shoes or keds are not permitted on the pitch.",
					"A valid college ID must be carried by every player",
					"The field referee's decision prevails. There will be no room for disagreement with the referee.",
					"If a player receives two yellow cards in two straight games (or a straight red card in one game), he will be suspended from the next match.",
					"Each half will consist of 10 minutes with 2-minute break between both halves",
					"Matches will be played 5-a side with 2 substitutions.",
					"Rolling substitutions are allowed at any point of the game.",
					"The winning team will proceed to the next round.",
					"The match will directly go into the penalty shootout if it ends in a tie, where each team will get 3 shots from the Centre of the pitch in an empty goal post.",
					"A player is allowed to play for one team only.",
					"All teams are advised to reach the ground on time, 10 minutes of waiting time will be given, failing to do so will result in a walkover of the absent team with a 1-0 deficit.",
					"Futsal rules will be applicable and will be strictly followed during every match.",
					"The squad may be disqualified outright if any player engages in unsporting behaviour",
				],
			},
		],
		contacts: [
			{
				name: "Swapnil Roy",
				phone: "+91 9330597391",
			},
			{
				name: "Indravo Ghosh",
				phone: "+91 8902010310",
			},
		],
		registration_amount: "Rs. 1000",
		registration_amount_iiest: "Rs. 1000",
		payment_link_iiest: "",
		payment_link: "",
		brochure_link: "",
	},
	{
		title: "Artival",
		eventId: "20",
		tagline:
			"An Exhibition on Creative Expression where art meets imagination",
		category: "SCAGE - Art Exhibition",
		type: "Individual",
		desc: "Artival is a celebration of creativity and artistic expression. This exhibition will showcase the works of talented artists from your college and beyond, providing a platform for them to share their unique perspectives with the community. Featuring a diverse range of art forms including paintings, sculptures, installations, and mixed media, Artistic Visions promises to be a visual feast for art enthusiasts. Whether you are an art lover or simply curious about the creative process, Artival is an event not to be missed. Comeexplore the depths of imagination and creativity that reside in the hearts and minds of our talented artists, and experience the magic of art in all its forms.",
		image: artival,
		startDate: "",
		endDate: "",
		rounds: [],
		contacts: [
			{
				name: "Devanshu Chatterjee",
				phone: "+91 73551 64558",
			},
			{
				name: "Nikhil Singh",
				phone: "+91 74898 38247",
			},
		],
	},
	{
		title: "Filmica",
		eventId: "21",
		tagline: "LIGHTS, CAMERA, REBECA",
		category: "Camerabuff - Workshop",
		type: "Individual",
		desc: "A workshop conducted by a special guest in association with Camerabuff where one can learn the ins and outs of filmmaking and explore the art of storytelling.",
		image: filmica,
		startDate: "",
		endDate: "",
		rounds: [],
		contacts: [
			{
				name: "Manisha Rao",
				phone: "9177309098",
			},
			{
				name: "Mahesh Bandlamudi",
				phone: "8639555844",
			},
		],
	},
	{
		title: "Cinessence",
		eventId: "22",
		tagline: "Popcorn, best friends, and a film to keep company.",
		category: "Camerabuff - Movie Night",
		type: "Individual",
		desc: "A fun-loaded movie night and to enjoy the culture of open air cinema screening with your friends and family.",
		image: cinessence,
		startDate: "",
		endDate: "",
		rounds: [],
		contacts: [
			{
				name: "Krishna Kant Drolia",
				phone: "8290259925",
			},
			{
				name: "Vasanthi Katragadda",
				phone: "8341410553",
			},
		],
	},
	{
		title: "Fiducia",
		eventId: "23",
		tagline: "Grace REBECA with elegance",
		category: "REBECA - Fashion Show",
		type: "Individual",
		desc: "Here's your chance to show off your fashion and woo the crowds as you walk the ramp, be the style icon you wanted to be. FIDUCIA, REBECA's fashion show event, is back with a bang!",
		image: fiducia,
		startDate: "",
		endDate: "",
		rounds: [],
		contacts: [
			{
				name: "Tiyasa Khan",
				phone: "8373047586",
			},
			{
				name: "Priyanshu Agarwal",
				phone: "7078741560",
			},
		],
	},
	{
		title: "Rangmanch",
		eventId: "24",
		tagline: "When words come to life on stage.",
		category: "Les Thespians - Theatrics",
		type: "Team",
		desc: "Les Thespians, The Dramatics Society of IIEST Shibpur, presents Rangmanch, an unforgettable live theatre as we present a captivating stage drama that will take you on an emotional journey. Our talented actors will bring the characters in the story to life right before your eyes, while our technical team creates a mesmerising atmosphere with their lighting, sound, and set design. Whether you're a fan of serious dramas or lighthearted comedies, our stage drama promises to entertain and leave you with something to think about long after the show is over.",
		image: rangmanch,
		startDate: "",
		endDate: "",
		rounds: [],
		contacts: [
			{
				name: "Kulin Kumar",
				phone: "7003768164",
			},
			{
				name: "Srinjoy Paul",
				phone: "9874755910",
			},
		],
	},
	{
		title: "Saturnalia",
		eventId: "25",
		tagline:
			"Rediscover the Suramya: A Captivating Exhibition of Timeless Photographs",
		category: "Catharsis - Exhibition",
		type: "Individual",
		desc: "A Photography exhibition, to draw the attention of budding shutterbugs and to provide them with an opportunity to showcase their talent.",
		image: saturnalia,
		startDate: "",
		endDate: "",
		rounds: [],
		contacts: [
			{
				name: "Nishita Chowdhury",
				phone: "+91 8777542763",
			},
			{
				name: "Shramana Chowdhury",
				phone: "+91 9002063900",
			},
			{ name: "Sumana Singh", phone: "+91 9800921724" },
			{ name: "Varnit Jain", phone: "+91 9879794823" },
		],
	},
	{
		title: "Typists' Tourney",
		eventId: "26",
		tagline: "Type with your fingers, think with your brain.",
		category: "CodeIIEST - Competition",
		type: "Individual",
		desc: "This REBECA, CodeIIEST brings you the chance to flaunt your touch typing. Head over to the Typists’ Journey and race to defend your high score!",
		image: typist,
		startDate: "",
		endDate: "",
		rounds: [],
		contacts: [
			{
				name: "Rajesh Penugonda",
				phone: "+91 99593 26280",
			},
			{
				name: "Kiranmoy Saha",
				phone: "+91 90830 45947",
			},
		],
	},
]
