export const teamDetails = [
	{
		title: "Secretary General",
		members: ["Neel Diganta Bhadra(CE)", "Rohan Jana (CE)"],
	},
	{
		title: "Finance",
		members: [
			"Mayank Kumar (EE)",
			"Parag Garg (AE)",
			"Mainak Mondal (CE)",
			"Saharsh Kumar (MIN)",
			"Samriddhi Mukhopadhyay (AE)",
		],
	},
	{
		title: "Cultural",
		members: [
			"Ayan Kamar (EE)",
			"Ayush Kumar Singh (ME)",
			"Vidushi Garg (CE)",
			"Aditya Badalaya (IT)",
			"Rajesh Kumar Jaiswar (CE)",
			"Sumit Godara (CE)",
			"Vipul Yadav (ME)",
			"Ashutosh Kumar Manjhi (ME)",
			"Ujjwal Chowdhary (ME)",
			"Rinku Kanwar (EE)",
			"Rajashree Banerjee (CE)",
			"Oishika Datta (CST)",
			"Shradhanand Prasad (ETC)",
		],
	},
	{
		title: "Event",
		members: [
			"Sayan Mitra (EE)",
			"Rudrapu Chalukya (CE)",
			"Tannistha Bag (ME)",
			"Tiyasa Khan (ME)",
			"Arnab Abhijit Sharma (ME)",
			"Abhinav Singh (EE)",
			"Abhijeet Anand (CE)",
			"Vasunith (CE)",
			"Priyanshu Agrawal (EE)",
			"Priyanshu Pramanick (ETC)",
			"Ajay Sarang (IT)",
			"Janhvi Singh Raghuvanshi (ME)",
			"Sanghamitra De (ETC)",
			"Sourik Saha (CST)",
		],
	},
	{
		title: "Resource Information",
		members: [
			"Shramana Chowdhury (CE)",
			"Shashank Srivastava (CST)",
			"Souvik Sengupta (EE)",
			"Karan Raj (ME)",
			"Jyotiprakash Roy (CST)",
			"Ravi Kumar Kesari (CE)",
			"Maruvada Narasimha Bhukta (MET)",
		],
	},
	{
		title: "Travel and Logistics",
		members: [
			"Soumya Roy (IT)",
			"Shubham Sahai (CE)",
			"Vivek Rawat(IT)",
			"Darshin D. Patel (CE)",
			"Chaitnaya Kumar (CE)",
			"Abhay Tanti (MIN)",
			"Amrish Kumar (CE)",
			"Debjyoti Bhattacharya (CE)",
			"Nishant Murarka (ETC)",
			"Dheeraj Gaur (CE)",
			"Sumit Sorrain (CST)",
		],
	},
	{
		title: "Sponsorship",
		members: [
			"Sumit Kumar (MIN)",
			"Bhavesh Sonkar (CE)",
			"Govinda Vinay Kumar (CE)",
			"Samudrala Vasanth (EE)",
			"Ayandeep Grain (MIN)",
			"Vasu Krishna Khemka (ME)",
			"Bhuvan Chandra Thokala (ME)",
			"Ishita Bhaya (EE)",
			"Mahesh Bandlamudi (ME)",
			"Sanjay Sharma (EE)",
			"Amartya Singh (ME)",
			"Dhanush Bala (ME)",
			"Dishan Bhuin (EE)",
			"Suyash Tiwari (ETC)",
		],
	},
	{
		title: "Publication",
		members: [
			"Ayan Chatterjee (CE)",
			"Innamuri Tarun (ARCH)",
			"Rakhi Jha (MIN)",
			"Indranil Bain (CST)",
			"Medarametla Avinash Choudary (ARCH)",
			"Sayan Ghosh (CE)",
			"Ajib KP (ARCH)",
			"Chandaswi Borra (MET)",
		],
	},
	{
		title: "Publicity",
		members: [
			"Rangan Das (MET)",
			"Bhavuk Dhanetia (CE)",
			"Shubham Saraff (EE)",
			"Rekha Sharma (AE)",
			"Deep Modak (IT)",
			"Ankur Roy Chowdhury (IT)",
			"Arghay Sornokar (MET)",
			"Rick Kundu (ETC)",
			"Supratim Bhattacharya (CE)",
			"Anurag Patel (EE)",
			"Devans Soni (CST)",
			"Saksham Kumar (EE)",
		],
	},
	{
		title: "Stage Decoration",
		members: [
			"Joseph Scaria James (ARCH)",
			"Amit Kumar (ARCH)",
			"Sathwik Bayyavarapu (ARCH)",
			"Aman Ramdas Deshmukh (ARCH)",
			"Falguni Joshi (ARCH)",
			"Goutham Popuri (ARCH)",
			"Apurv Manoj Mirgule (ARCH)",
		],
	},
	{
		title: "Business and Alumni meet",
		members: [
			"Raushan Singh (IT)",
			"Prajwal Velupula (ETC)",
			"Amrit Tripathi (EE)",
			"Prajwal Kashinath Nakade (CST)",
			"Sarvesh Dubey (ETC)",
			"Aditya Nilesh Dhamne (AE)",
			"Arnav Anand (ME)",
			"Disha Trivedi (IT)",
			"Harshal Sharma (ETC)",
			"Amrit Keshari (MIN)",
			"Ayush Goyal (ETC)",
			"Raushan Das (CST)",
			"Aman Tiwari (MET)",
		],
	},
	{
		title: "Competitions and Seminars",
		members: [
			"Shantanu Debnath (CST)",
			"Manglesh Ranjan (MIN)",
			"Surajit Dutta (EE)",
			"Singpuram Venkata Satya Sai Raghav (ME)",
			"Madhav Kumar (MIN)",
			"Utsav Kumar Vishwakarma (EE)",
			"Sanjeet Kumar (MIN)",
			"Piyal Sarkar Turjo (CST)",
			"Aman Singh (IT)",
			"Ankit kumar Hore (MIN)",
		],
	},
	{
		title: "Web Development",
		members: ["Dhritin Dutta (CST)", "Devanshu Chatterjee (IT)"],
	},
	{
		title: "Refreshments",
		members: [
			"Debmalya Hembram (EE)",
			"Pulok Halder (AE)",
			"Aditya Anand (IT)",
			"Ashutosh (ME)",
			"Shailendra (IT)",
			"Dipak Bobonga (MIN)",
			"Ashwini Ranjan (ETC)",
			"Yanamadala Jaya Ram (ME)",
			"Aditya Didolkar (AE)",
			"Ketan Mohan Masurkar (ME)",
			"Md. Asif Fuzail (ETC)",
		],
	},
	{
		title: "Volunteers",
		members: [
			"Vishal (CE)",
			"Prahalad Dutta (CE)",
			"Abhishek Gajanan Jare (ME)",
			"Malloth Vijay (ME)",
			"Vishal Kumar (CHST, M-Tech, 2nd year)",
			"Gourab Chatterjee (CE)",
			"Vijay Prakash (CE)",
			"Rishikesh Kumar (CE)",
			"Pratik (MIN)",
			"Rahul Kumar (IT)",
			"Rajkumar Yadav (MIN)",
			"Arneet Dutta (EE)",
		],
	},
	{
		title: "Photography",
		members: [
			"Rahul Meena (CE)",
			"Anan Joy Anthony (AE)",
			"D. Aravind (EE)",
			"Arshiya (ETC)",
			"Talasila Bharath Kumar (AE)",
			"Avi Ambast (ME)",
			"Tanisha Kumari (ETC)",
			"Rajat Rahar (EE)",
			"Puru Maharshi (MET)",
			"Shivanshu Gupta (CE)",
			"Pratik Sitaram Girade (CST)",
			"Karan Mahato (ME)",
		],
	},
	{
		title: "Joint Secretary",
		members: ["Harsh Joshi (CE)", "Sankalp Sanjay Mukhedkar (AE)"],
	},
	{
		title: "BECA Magazine",
		members: [
			"Shubham (CST)",
			"Kshitij Gupta (ME)",
			"Nishita Chowdhury (ME)",
			"Aprajita Sen (ETC)",
			"Gurusha Rahul (IT)",
			"Tathagata Ghosh (IT)",
			"Krishna kant Drolia (CE)",
			"Suryansh Pandey (IT)",
			"Rajneesh Pathak (CE)",
			"Astitva Nath Mishra (EE)",
			"Avishikta Das (MIN)",
		],
	},
]
